AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fake_imds_route
  
  Sample SAM Template for fake_imds_route

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Parameters:
  FakeImdsInstanceId:
    Type: String
    Description: The instance id of the fake imds server.

Resources:
  FakeImdsRouteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: FakeImdsRoute/
      Handler: FakeImdsRoute
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies:
        - arn:aws:iam::aws:policy/job-function/NetworkAdministrator
      Events:
        EC2RunTrigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "aws.ec2"
              detail:
                eventSource:
                  - "ec2.amazonaws.com"
                eventName:
                  - "RunInstances"

Outputs:
  FakeImdsRouteFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt FakeImdsRouteFunction.Arn
  FakeImdsRouteFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FakeImdsRouteFunctionRole.Arn
