AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fake_imds_route
  
  Sample SAM Template for fake_imds_route

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

#Parameters:
#  FakeImdsInstanceId:
#    Type: String
#    Description: The instance id of the fake imds server.
#  ActiveVpc:
#    Type: String
#    Description: VPC's to operate in, it should be the same VPC the fake IMDS instance resides in.
#  ActiveSubnets:
#    Type: CommaDelimitedList
#    Description: List of Subnets to operate on, they should exist in ActiveVpc and exclude the subnet the fake imds resides in.

Resources:
  FakeImdsRouteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: FakeImdsRoute/
      Handler: FakeImdsRoute
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        EC2RunTrigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "aws.ec2"
              detail:
                eventSource:
                  - "ec2.amazonaws.com"
                eventName:
                  - "RunInstances"
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          FakeImdsInstanceId: "i-047ff7ceff77ff0d5"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FakeImdsRouteAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FakeImdsRouteFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt FakeImdsRouteFunction.Arn
  FakeImdsRouteFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FakeImdsRouteFunctionRole.Arn
